"""Adicionando colunas a agendamentos

Revision ID: 3a62663b8422
Revises: 
Create Date: 2024-11-07 01:20:17.511339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a62663b8422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('setor', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('servico', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('horario', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')
        batch_op.drop_column('cpf')
        batch_op.drop_column('nome')
        batch_op.drop_column('horario')
        batch_op.drop_column('data')
        batch_op.drop_column('servico')
        batch_op.drop_column('setor')
        batch_op.drop_column('local')

    # ### end Alembic commands ###
