"""Ajuste no tamanho do campo CPF

Revision ID: ada165c9f641
Revises: 3a62663b8422
Create Date: 2024-11-07 01:53:55.563452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada165c9f641'
down_revision = '3a62663b8422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.drop_column('horario')
        batch_op.drop_column('data')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('horario', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
